const listOfCountiers = [
  "Algeria",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Azerbaijan",
  "Belarus",
  "Bolivia",
  "Brazil",
  "Canada",
  "Chad",
  "China",
  "Colombia",
  "Democratic Republic of the Congo",
  "Costa Rica",
  "Estonia",
  "Egypt",
  "Ecuador",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greenland",
  "Guinea",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Italy",
  "Kazakhstan",
  "Kenya",
  "Kyrgyzstan",
  "Latvia",
  "Lithuania",
  "Libya",
  "Malawi",
  "Malaysia",
  "Mexico",
  "Moldova",
  "Mongolia",
  "Namibia",
  "Niger",
  "Nigeria",
  "Pakistan",
  "Peru",
  "Philippines",
  "Russia",
  "Saudi Arabia",
  "South Africa",
  "Sudan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Turkmenistan",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States of America",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Zimbabwe",
];

export default listOfCountiers;
